-- Truncate all data while keeping schema (MySQL)
USE BaBLog_Test_DB;

SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE meal_food;
TRUNCATE TABLE meal_log;
TRUNCATE TABLE meal;
TRUNCATE TABLE member_nutrient_daily;
TRUNCATE TABLE member_nutrient;
TRUNCATE TABLE daily_report;
TRUNCATE TABLE weekly_report;
TRUNCATE TABLE goal;
TRUNCATE TABLE batch_failure_log;
TRUNCATE TABLE food;
TRUNCATE TABLE member;

-- Spring Batch metadata (optional reset)
TRUNCATE TABLE BATCH_STEP_EXECUTION_CONTEXT;
TRUNCATE TABLE BATCH_STEP_EXECUTION;
TRUNCATE TABLE BATCH_JOB_EXECUTION_CONTEXT;
TRUNCATE TABLE BATCH_JOB_EXECUTION_PARAMS;
TRUNCATE TABLE BATCH_JOB_EXECUTION;
TRUNCATE TABLE BATCH_JOB_INSTANCE;

SET FOREIGN_KEY_CHECKS = 1;
